POST https://texttospeech.googleapis.com/v1/text:synthesize
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImMxNGY3Nzg5MzhhZjY0MDc3OGRhYTE2MjhlN2I2YzM5NmUyNTE4ZDUifQ.eyJpc3MiOiJ0ZXh0MnNwZWVjaC1zeW50aGVzaXplckB3Y2FzZy1hZGEtYXBwLWRldi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInN1YiI6InRleHQyc3BlZWNoLXN5bnRoZXNpemVyQHdjYXNnLWFkYS1hcHAtZGV2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiYXVkIjoiaHR0cHM6Ly90ZXh0dG9zcGVlY2guZ29vZ2xlYXBpcy5jb20vIiwiaWF0IjoxNTgwNjkyNjQ1LCJleHAiOjE1ODA2OTYyNDV9.hRdwcK5s9nTXCqMwJSXNfJV1EXKhi2ZAv5GOnQdVn-IiNtkPsSFH-I12YUtrhw50ZCyZb75i0TpvPhZ8kYaQn3_rmbuJ53dMbGuM3Kezf55--t8i7hlxxIIR1ig99BuFNHZ-gERs-DPBmOQGPcV6SloDPIenN9zW0R68BZZIkiwFGEd0a1Ud-zLvwZ18S4dg5ucEq_187uImOJgB2S20mbyzvmcJ41qSFMcvHRQ5WSXyBzJtocS2BLT3XOL3QjvwCwmqMGBz-_QUquqImO9s-zalzTeTwMq8zVVuOk9r5eYcea58kqx602jslqOOOrvd8aN-MM04IaUqsoRLrIZtkw
Accept: application/json

{
  "audioConfig": {
    "audioEncoding": "LINEAR16",
    "pitch": -14,
    "speakingRate": 1,
    "sampleRateHertz": 24000,
    "volumeGainDb": 0,
    "effectsProfileId": [ "handset-class-device" ]
  },
  "input": {
    "text": "Call me Ishmael."
  },
  "voice": {
    "languageCode": "en-US",
    "name": "en-US-Wavenet-D"
  },
}

###
