// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  grayscale: string;
  invert: string;
}
export const cssExports: CssExports;
export default cssExports;
