// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'plugin-element': string;
  'plugin-element-scalable': string;
  'plugin-element-toggleable': string;
}
export const cssExports: CssExports;
export default cssExports;
