// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  highlightLinksBlock: string;
  highlightLinksBorder: string;
  highlightLinksBoth: string;
}
export const cssExports: CssExports;
export default cssExports;
