// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  Large: string;
  Normal: string;
  XLarge: string;
  XXLarge: string;
  hidden: string;
  key: string;
  'key-row': string;
  keyboard: string;
  visible: string;
  'wcasg-ada-app-keyboard-modal': string;
}
export const cssExports: CssExports;
export default cssExports;
