// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  hidden: string;
  key: string;
  'key-row': string;
  keyboard: string;
  visible: string;
  'wcasg-ada-app-keyboard-modal': string;
}
export const cssExports: CssExports;
export default cssExports;
