// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emphasizeHover': string;
  'emphasizeTitles': string;
  'hideImages': string;
  'highlightForms': string;
  'highlightLinksBlock': string;
  'highlightLinksBorder': string;
  'highlightLinksBoth': string;
  'keyboardNavigationFocus': string;
  'largeCursor': string;
  'readableFonts': string;
  'stopGlobalAnimations': string;
}
export const cssExports: CssExports;
export default cssExports;
