import React, { useEffect } from 'react';
import PluginManager from 'classes/plugin/manager';
import { PluginComponent } from 'components/plugin';
import { Plugin } from '@/enum';
import config from 'config';

import PageNavigationComponent from 'plugins/page-navigation';
import PageNavigationPlugin from 'plugins/page-navigation/plugin';

import VirtualKeyboardComponent from 'plugins/virtual-keyboard';
import VirtualKeyboardPlugin from 'plugins/virtual-keyboard/plugin';

import { Selectors } from 'state/redux/selectors';
import { State } from 'state/redux/state';
import styles from './styles.scss';

// import BlackAndYellowComponent from 'plugins/black-and-yellow';
// import DarkContrastComponent from 'plugins/dark-contrast';
// import EmphasizeHoverComponent from 'plugins/emphasize-hover';
// import EmphasizeTitlesComponent from 'plugins/emphasize-titles';
// import GrayscaleComponent from 'plugins/grayscale';
// import HideImagesComponent from 'plugins/hide-images';
// import HighlightFormsComponent from 'plugins/highlight-forms';
// import HighlightLinksComponent from 'plugins/highlight-links';
// import InvertColorsComponent from 'plugins/invert-colors';
// import KeyboardNavigationComponent from 'plugins/keyboard-navigation';
// import LargeCursorComponent from 'plugins/large-cursor';
// import LightContrastComponent from 'plugins/light-contrast';
// import ReadableFontsComponent from 'plugins/readable-fonts';
// import StopAnimationsComponent from 'plugins/stop-animations';
// import TextToSpeechComponent from 'plugins/text-to-speech';
// import TooltipComponent from 'plugins/tooltip';
//
// import HighlightLinksPlugin from 'plugins/highlight-links/plugin';
// import KeyboardNavigationPlugin from 'plugins/keyboard-navigation/plugin';
// import TextToSpeechPlugin from 'plugins/text-to-speech/plugin';
//
// import HighlightLinksComponent from 'plugins/highlight-links';
// import HighlightLinksPlugin from 'plugins/highlight-links/plugin';
// import KeyboardNavigationComponent from 'plugins/keyboard-navigation';
// import KeyboardNavigationPlugin from 'plugins/keyboard-navigation/plugin';
import TextToSpeechComponent from 'plugins/text-to-speech';
import TextToSpeechPlugin from 'plugins/text-to-speech/plugin';

const Widget = ({ state, actions }: { state: State; actions: any }) => {
  useEffect(() => {
    // One-time dispatch of enabled plugins on initial render.
    const ids = new Selectors(state).getEnabledIds();
    ids.forEach((id: string) => actions.enable(id));
  }, []);
  return (
    <div className={styles.modal}>
      <h2>{config.widgetTitle}</h2>
      <div className={styles.modalContainer}>
        {PluginManager.getInstance().pluginsAutoGenerated.map(
          (plugin: Plugin) => (
            <PluginComponent
              key={plugin.id}
              state={state}
              actions={actions}
              id={plugin.id}
            />
          )
        )}
        <TextToSpeechComponent
          key={TextToSpeechPlugin.id}
          state={state}
          actions={actions}
          id={TextToSpeechPlugin.id}
        />
        <PageNavigationComponent
          key={PageNavigationPlugin.id}
          state={state}
          actions={actions}
          id={PageNavigationPlugin.id}
        />
        <VirtualKeyboardComponent
          key={VirtualKeyboardPlugin.id}
          state={state}
          actions={actions}
          id={VirtualKeyboardPlugin.id}
        />
      </div>
    </div>
  );
};

export default Widget;
