import { PluginsAutoGenerated } from '@/globals';
import { PluginComponent } from 'components/plugin';
import config from 'config';

import PageNavigationComponent from 'plugins/page-navigation';
import PageNavigationPlugin from 'plugins/page-navigation/plugin';

// import BlackAndYellowComponent from 'plugins/black-and-yellow';
// import DarkContrastComponent from 'plugins/dark-contrast';
// import EmphasizeHoverComponent from 'plugins/emphasize-hover';
// import EmphasizeTitlesComponent from 'plugins/emphasize-titles';
// import GrayscaleComponent from 'plugins/grayscale';
// import HideImagesComponent from 'plugins/hide-images';
// import HighlightFormsComponent from 'plugins/highlight-forms';
// import HighlightLinksComponent from 'plugins/highlight-links';
// import InvertColorsComponent from 'plugins/invert-colors';
// import KeyboardNavigationComponent from 'plugins/keyboard-navigation';
// import LargeCursorComponent from 'plugins/large-cursor';
// import LightContrastComponent from 'plugins/light-contrast';
// import ReadableFontsComponent from 'plugins/readable-fonts';
// import StopAnimationsComponent from 'plugins/stop-animations';
// import TextToSpeechComponent from 'plugins/text-to-speech';
// import TooltipComponent from 'plugins/tooltip';
//
// import HighlightLinksPlugin from 'plugins/highlight-links/plugin';
// import KeyboardNavigationPlugin from 'plugins/keyboard-navigation/plugin';
// import TextToSpeechPlugin from 'plugins/text-to-speech/plugin';
//
// import HighlightLinksComponent from 'plugins/highlight-links';
// import HighlightLinksPlugin from 'plugins/highlight-links/plugin';
// import KeyboardNavigationComponent from 'plugins/keyboard-navigation';
// import KeyboardNavigationPlugin from 'plugins/keyboard-navigation/plugin';
// import TextToSpeechComponent from 'plugins/text-to-speech';
// import TextToSpeechPlugin from 'plugins/text-to-speech/plugin';

import React from 'react';
import styles from './styles.scss';

export const WidgetNew = ({ state, actions }: any) => (
  <div className={styles.modal}>
    <h2>{config.widgetTitle}</h2>
    <div className={styles.modalContainer}>
      {PluginsAutoGenerated.map(plugin => (
        <PluginComponent
          key={plugin.id}
          state={state}
          actions={actions}
          id={plugin.id}
        />
      ))}
      <PageNavigationComponent
        key={PageNavigationPlugin.id}
        state={state}
        actions={actions}
        id={PageNavigationPlugin.id}
      />
    </div>
  </div>
);
