import { PluginsAutoGenerated } from '@/globals';
import { PluginComponent } from 'components/plugin';
import config from 'config';

import HighlightLinksComponent from 'plugins-new/highlight-links';
import HighlightLinksPlugin from 'plugins-new/highlight-links/plugin';
import KeyboardNavigationComponent from 'plugins-new/keyboard-navigation';
import KeyboardNavigationPlugin from 'plugins-new/keyboard-navigation/plugin';
import TextToSpeechComponent from 'plugins-new/text-to-speech';
import TextToSpeechPlugin from 'plugins-new/text-to-speech/plugin';

import React from 'react';
import styles from './styles.scss';

export const WidgetNew = ({ state, actions }: any) => (
  <div className={styles.modal}>
    <h2>{config.widgetTitle}</h2>
    <div className={styles.modalContainer}>
      <HighlightLinksComponent
        key={HighlightLinksPlugin.id}
        state={state}
        actions={actions}
        id={HighlightLinksPlugin.id}
      />
      <KeyboardNavigationComponent
        key={KeyboardNavigationPlugin.id}
        state={state}
        actions={actions}
        id={KeyboardNavigationPlugin.id}
      />
      <TextToSpeechComponent
        key={TextToSpeechPlugin.id}
        state={state}
        actions={actions}
        id={TextToSpeechPlugin.id}
      />
      {PluginsAutoGenerated.map(plugin => (
        <PluginComponent
          key={plugin.id}
          state={state}
          actions={actions}
          id={plugin.id}
        />
      ))}
    </div>
  </div>
);
//
// export class WidgetOld extends React.Component<{}> {
//   public render() {
//     return (
//       <div className={styles.modal}>
//         <h2>{config.widgetTitle}</h2>
//         <div className={styles.modalContainer}>
//           {Plugins.map((element: { template: any }) => {
//             return element.template;
//           })}
//         </div>
//       </div>
//     );
//   }
// }
