// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'wcasg-ada-app-tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
