export enum Ids {
  BlackAndYellow = 'black-and-yellow',
  DarkContrast = 'dark-contrast',
  EmphasizeHover = 'emphasize-hover',
  EmphasizeTitles = 'emphasize-titles',
  FontSize = 'font-size',
  Grayscale = 'grayscale',
  HideImages = 'hide-images',
  HighlightForms = 'highlight-forms',
  HighlightLinks = 'highlight-links',
  InvertColors = 'invert-colors',
  KeyboardNavigation = 'keyboard-navigation',
  LargeCursor = 'large-cursor',
  LetterSpacing = 'text-spacing',
  LightContrast = 'light-contrast',
  MuteAudio = 'mute-audio',
  PageNavigation = 'page-navigation',
  ReadableFonts = 'readable-fonts',
  StopAnimations = 'stop-animations',
  TextToSpeech = 'text-to-speech',
  Tooltip = 'tooltip',
  VirtualKeyboard = 'virtual-keyboard'
}
