import { Plugin } from '@/enum';

import BlackAndYellow from 'plugins-new/black-and-yellow/plugin';
import DarkContrast from 'plugins-new/dark-contrast/plugin';
import EmphasizeHover from 'plugins-new/emphasize-hover/plugin';
import EmphasizeTitles from 'plugins-new/emphasize-titles/plugin';
import Grayscale from 'plugins-new/grayscale/plugin';
import HideImages from 'plugins-new/hide-images/plugin';
import HighlightForms from 'plugins-new/highlight-forms/plugin';
import HighlightLinks from 'plugins-new/highlight-links/plugin';
import InvertColors from 'plugins-new/invert-colors/plugin';
import KeyboardNavigation from 'plugins-new/keyboard-navigation/plugin';
import LargeCursor from 'plugins-new/large-cursor/plugin';
import LightContrast from 'plugins-new/light-contrast/plugin';
import ReadableFonts from 'plugins-new/readable-fonts/plugin';
import StopAnimations from 'plugins-new/stop-animations/plugin';
import TextToSpeech from 'plugins-new/text-to-speech/plugin';
import Tooltip from 'plugins-new/tooltip/plugin';

export const PluginsCustomized: Plugin[] = [
  EmphasizeTitles,
  HideImages,
  HighlightLinks,
  KeyboardNavigation,
  TextToSpeech
];

export const PluginsAutoGenerated: Plugin[] = [
  BlackAndYellow,
  DarkContrast,
  EmphasizeHover,
  Grayscale,
  HighlightForms,
  InvertColors,
  LargeCursor,
  LightContrast,
  ReadableFonts,
  StopAnimations,
  Tooltip
];

export const Plugins: Plugin[] = [
  ...PluginsCustomized,
  ...PluginsAutoGenerated
];
