import { Plugin } from '@/enum';

import BlackAndYellow from 'plugins-new/black-and-yellow/plugin';
import DarkContrast from 'plugins-new/dark-contrast/plugin';
import EmphasizeHover from 'plugins-new/emphasize-hover/plugin';
import EmphasizeTitles from 'plugins-new/emphasize-titles/plugin';
import FontSize from 'plugins-new/font-size/plugin';
import Grayscale from 'plugins-new/grayscale/plugin';
import HideImages from 'plugins-new/hide-images/plugin';
import HighlightForms from 'plugins-new/highlight-forms/plugin';
import HighlightLinks from 'plugins-new/highlight-links/plugin';
import InvertColors from 'plugins-new/invert-colors/plugin';
import KeyboardNavigation from 'plugins-new/keyboard-navigation/plugin';
import LargeCursor from 'plugins-new/large-cursor/plugin';
import LetterSpacing from 'plugins-new/letter-spacing/plugin';
import LightContrast from 'plugins-new/light-contrast/plugin';
import MuteAudio from 'plugins-new/mute-audio/plugin';
import PageNavigation from 'plugins-new/page-navigation/plugin';
import ReadableFonts from 'plugins-new/readable-fonts/plugin';
import StopAnimations from 'plugins-new/stop-animations/plugin';
import TextToSpeech from 'plugins-new/text-to-speech/plugin';
import Tooltip from 'plugins-new/tooltip/plugin';

export const Plugins: Plugin[] = [
  BlackAndYellow,
  DarkContrast,
  EmphasizeHover,
  EmphasizeTitles,
  FontSize,
  Grayscale,
  HideImages,
  HighlightForms,
  HighlightLinks,
  InvertColors,
  KeyboardNavigation,
  LargeCursor,
  LetterSpacing,
  LightContrast,
  MuteAudio,
  PageNavigation,
  ReadableFonts,
  StopAnimations,
  TextToSpeech,
  Tooltip
];

export const PluginsCustomized: Plugin[] = Plugins.filter(
  plugin => plugin.customComponent
);

export const PluginsAutoGenerated: Plugin[] = Plugins.filter(
  plugin => !plugin.customComponent
);
